/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *action_C;
    QAction *action_D;
    QAction *action_H;
    QWidget *centralWidget;
    QPushButton *percent;
    QPushButton *clear_entry;
    QPushButton *radical_sign;
    QPushButton *clear;
    QPushButton *square;
    QPushButton *delete_2;
    QPushButton *reciprocal;
    QPushButton *divide;
    QToolButton *history;
    QToolButton *memory;
    QPushButton *mem_clear;
    QPushButton *mm_read;
    QPushButton *mem_plus;
    QPushButton *mem_minus;
    QPushButton *mem_save;
    QPushButton *clear_3;
    QTextEdit *monitor1;
    QTextEdit *monitor3;
    QPushButton *number_7;
    QPushButton *number_6;
    QPushButton *times;
    QPushButton *number_9;
    QPushButton *number_4;
    QPushButton *minus;
    QPushButton *number_8;
    QPushButton *number_5;
    QPushButton *number_1;
    QPushButton *point;
    QPushButton *plus;
    QPushButton *number_3;
    QPushButton *negate;
    QPushButton *equal;
    QPushButton *number_2;
    QPushButton *number_0;
    QTextEdit *monitor0;
    QTextEdit *monitor2;
    QPushButton *clear_2;
    QTextEdit *mem_his;
    QPushButton *mem_clear_2;
    QPushButton *mem_minus_2;
    QPushButton *mm_read_2;
    QPushButton *mem_plus_2;
    QPushButton *mem_save_2;
    QPushButton *F_E;
    QPushButton *HYP;
    QPushButton *GRD;
    QPushButton *square_2;
    QPushButton *sqrt;
    QPushButton *arrow;
    QPushButton *pi;
    QPushButton *Left_Pare;
    QPushButton *factorial;
    QPushButton *negate_2;
    QPushButton *N4;
    QPushButton *N7;
    QPushButton *Right_Pare;
    QPushButton *power_y;
    QPushButton *power_ten;
    QPushButton *Clear_entry;
    QPushButton *N1;
    QPushButton *N5;
    QPushButton *N8;
    QPushButton *N0;
    QPushButton *sin;
    QPushButton *log;
    QPushButton *Clear;
    QPushButton *N2;
    QPushButton *divide_2;
    QPushButton *cos;
    QPushButton *Delete_1;
    QPushButton *times_2;
    QPushButton *minus_2;
    QPushButton *Mod;
    QPushButton *N6;
    QPushButton *Exp;
    QPushButton *tan;
    QPushButton *point_2;
    QPushButton *plus_2;
    QPushButton *N3;
    QPushButton *equal_2;
    QPushButton *N9;
    QPushButton *mode;
    QPushButton *dms;
    QPushButton *N_Reagan;
    QPushButton *deg;
    QPushButton *ln;
    QPushButton *cos_01;
    QPushButton *N_power;
    QPushButton *cube;
    QPushButton *reciprocal_2;
    QPushButton *sin_01;
    QPushButton *tan_01;
    QPushButton *cosh;
    QPushButton *sinh;
    QPushButton *tanh;
    QPushButton *cosh_01;
    QPushButton *sinh_01;
    QPushButton *tanh_01;
    QPushButton *arrow_2;
    QPushButton *HYP_2;
    QMenuBar *menuBar;
    QMenu *menu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(902, 800);
        MainWindow->setMinimumSize(QSize(902, 800));
        MainWindow->setMaximumSize(QSize(902, 800));
        MainWindow->setSizeIncrement(QSize(902, 0));
        QFont font;
        font.setUnderline(false);
        MainWindow->setFont(font);
        QIcon icon;
        icon.addFile(QStringLiteral(":/myImages/image/back.jpg"), QSize(), QIcon::Disabled, QIcon::On);
        icon.addFile(QStringLiteral(":/myImages/image/back.jpg"), QSize(), QIcon::Active, QIcon::On);
        MainWindow->setWindowIcon(icon);
        action_C = new QAction(MainWindow);
        action_C->setObjectName(QStringLiteral("action_C"));
        action_D = new QAction(MainWindow);
        action_D->setObjectName(QStringLiteral("action_D"));
        action_H = new QAction(MainWindow);
        action_H->setObjectName(QStringLiteral("action_H"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        percent = new QPushButton(centralWidget);
        percent->setObjectName(QStringLiteral("percent"));
        percent->setGeometry(QRect(10, 260, 121, 71));
        QFont font1;
        font1.setPointSize(18);
        font1.setBold(true);
        font1.setWeight(75);
        percent->setFont(font1);
        percent->setFocusPolicy(Qt::NoFocus);
        clear_entry = new QPushButton(centralWidget);
        clear_entry->setObjectName(QStringLiteral("clear_entry"));
        clear_entry->setGeometry(QRect(10, 340, 121, 71));
        clear_entry->setFont(font1);
        radical_sign = new QPushButton(centralWidget);
        radical_sign->setObjectName(QStringLiteral("radical_sign"));
        radical_sign->setGeometry(QRect(140, 260, 121, 71));
        radical_sign->setFont(font1);
        clear = new QPushButton(centralWidget);
        clear->setObjectName(QStringLiteral("clear"));
        clear->setGeometry(QRect(140, 340, 121, 71));
        clear->setFont(font1);
        square = new QPushButton(centralWidget);
        square->setObjectName(QStringLiteral("square"));
        square->setGeometry(QRect(270, 260, 121, 71));
        square->setFont(font1);
        delete_2 = new QPushButton(centralWidget);
        delete_2->setObjectName(QStringLiteral("delete_2"));
        delete_2->setGeometry(QRect(270, 340, 121, 71));
        delete_2->setFont(font1);
        reciprocal = new QPushButton(centralWidget);
        reciprocal->setObjectName(QStringLiteral("reciprocal"));
        reciprocal->setGeometry(QRect(400, 260, 121, 71));
        reciprocal->setFont(font1);
        divide = new QPushButton(centralWidget);
        divide->setObjectName(QStringLiteral("divide"));
        divide->setGeometry(QRect(400, 340, 121, 71));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush);
        divide->setPalette(palette);
        divide->setFont(font1);
        history = new QToolButton(centralWidget);
        history->setObjectName(QStringLiteral("history"));
        history->setGeometry(QRect(530, 20, 91, 41));
        QFont font2;
        font2.setBold(true);
        font2.setUnderline(false);
        font2.setWeight(75);
        history->setFont(font2);
        memory = new QToolButton(centralWidget);
        memory->setObjectName(QStringLiteral("memory"));
        memory->setGeometry(QRect(620, 20, 91, 41));
        QFont font3;
        font3.setBold(true);
        font3.setWeight(75);
        memory->setFont(font3);
        mem_clear = new QPushButton(centralWidget);
        mem_clear->setObjectName(QStringLiteral("mem_clear"));
        mem_clear->setGeometry(QRect(10, 210, 91, 41));
        QFont font4;
        font4.setPointSize(12);
        font4.setBold(false);
        font4.setWeight(50);
        mem_clear->setFont(font4);
        mm_read = new QPushButton(centralWidget);
        mm_read->setObjectName(QStringLiteral("mm_read"));
        mm_read->setGeometry(QRect(110, 210, 91, 41));
        mm_read->setFont(font4);
        mem_plus = new QPushButton(centralWidget);
        mem_plus->setObjectName(QStringLiteral("mem_plus"));
        mem_plus->setGeometry(QRect(210, 210, 91, 41));
        mem_plus->setFont(font4);
        mem_minus = new QPushButton(centralWidget);
        mem_minus->setObjectName(QStringLiteral("mem_minus"));
        mem_minus->setGeometry(QRect(310, 210, 91, 41));
        mem_minus->setFont(font4);
        mem_save = new QPushButton(centralWidget);
        mem_save->setObjectName(QStringLiteral("mem_save"));
        mem_save->setGeometry(QRect(410, 210, 91, 41));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        mem_save->setPalette(palette1);
        mem_save->setFont(font4);
        mem_save->setAutoDefault(false);
        clear_3 = new QPushButton(centralWidget);
        clear_3->setObjectName(QStringLiteral("clear_3"));
        clear_3->setEnabled(true);
        clear_3->setGeometry(QRect(850, 700, 41, 31));
        clear_3->setFont(font3);
        clear_3->setContextMenuPolicy(Qt::DefaultContextMenu);
        clear_3->setIconSize(QSize(30, 30));
        monitor1 = new QTextEdit(centralWidget);
        monitor1->setObjectName(QStringLiteral("monitor1"));
        monitor1->setGeometry(QRect(10, 100, 511, 81));
        QFont font5;
        font5.setPointSize(36);
        font5.setBold(true);
        font5.setWeight(75);
        monitor1->setFont(font5);
        monitor1->setLayoutDirection(Qt::RightToLeft);
        monitor1->setAutoFillBackground(false);
        monitor1->setInputMethodHints(Qt::ImhNone);
        monitor1->setFrameShape(QFrame::Box);
        monitor1->setLineWidth(0);
        monitor1->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        monitor1->setTabChangesFocus(false);
        monitor3 = new QTextEdit(centralWidget);
        monitor3->setObjectName(QStringLiteral("monitor3"));
        monitor3->setEnabled(true);
        monitor3->setGeometry(QRect(530, 60, 361, 671));
        monitor3->setFont(font1);
        monitor3->setLayoutDirection(Qt::RightToLeft);
        monitor3->setFrameShape(QFrame::Box);
        monitor3->setLineWidth(0);
        monitor3->setReadOnly(false);
        number_7 = new QPushButton(centralWidget);
        number_7->setObjectName(QStringLiteral("number_7"));
        number_7->setGeometry(QRect(10, 420, 121, 71));
        QFont font6;
        font6.setPointSize(20);
        font6.setBold(true);
        font6.setWeight(75);
        number_7->setFont(font6);
        number_7->setFocusPolicy(Qt::NoFocus);
        number_6 = new QPushButton(centralWidget);
        number_6->setObjectName(QStringLiteral("number_6"));
        number_6->setGeometry(QRect(270, 500, 121, 71));
        number_6->setFont(font6);
        times = new QPushButton(centralWidget);
        times->setObjectName(QStringLiteral("times"));
        times->setGeometry(QRect(400, 420, 121, 71));
        QPalette palette2;
        QBrush brush1(QColor(240, 240, 240, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(235, 235, 235, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        times->setPalette(palette2);
        times->setFont(font1);
        number_9 = new QPushButton(centralWidget);
        number_9->setObjectName(QStringLiteral("number_9"));
        number_9->setGeometry(QRect(270, 420, 121, 71));
        number_9->setFont(font6);
        number_4 = new QPushButton(centralWidget);
        number_4->setObjectName(QStringLiteral("number_4"));
        number_4->setGeometry(QRect(10, 500, 121, 71));
        number_4->setFont(font6);
        minus = new QPushButton(centralWidget);
        minus->setObjectName(QStringLiteral("minus"));
        minus->setGeometry(QRect(400, 500, 121, 71));
        minus->setFont(font1);
        number_8 = new QPushButton(centralWidget);
        number_8->setObjectName(QStringLiteral("number_8"));
        number_8->setGeometry(QRect(140, 420, 121, 71));
        number_8->setFont(font6);
        number_5 = new QPushButton(centralWidget);
        number_5->setObjectName(QStringLiteral("number_5"));
        number_5->setGeometry(QRect(140, 500, 121, 71));
        number_5->setFont(font6);
        number_1 = new QPushButton(centralWidget);
        number_1->setObjectName(QStringLiteral("number_1"));
        number_1->setGeometry(QRect(10, 580, 121, 71));
        number_1->setFont(font6);
        number_1->setFocusPolicy(Qt::NoFocus);
        point = new QPushButton(centralWidget);
        point->setObjectName(QStringLiteral("point"));
        point->setGeometry(QRect(270, 660, 121, 71));
        point->setFont(font1);
        plus = new QPushButton(centralWidget);
        plus->setObjectName(QStringLiteral("plus"));
        plus->setGeometry(QRect(400, 580, 121, 71));
        plus->setFont(font1);
        number_3 = new QPushButton(centralWidget);
        number_3->setObjectName(QStringLiteral("number_3"));
        number_3->setGeometry(QRect(270, 580, 121, 71));
        number_3->setFont(font6);
        negate = new QPushButton(centralWidget);
        negate->setObjectName(QStringLiteral("negate"));
        negate->setGeometry(QRect(10, 660, 121, 71));
        negate->setFont(font1);
        equal = new QPushButton(centralWidget);
        equal->setObjectName(QStringLiteral("equal"));
        equal->setGeometry(QRect(400, 660, 121, 71));
        equal->setFont(font1);
        number_2 = new QPushButton(centralWidget);
        number_2->setObjectName(QStringLiteral("number_2"));
        number_2->setGeometry(QRect(140, 580, 121, 71));
        number_2->setFont(font6);
        number_0 = new QPushButton(centralWidget);
        number_0->setObjectName(QStringLiteral("number_0"));
        number_0->setGeometry(QRect(140, 660, 121, 71));
        number_0->setFont(font6);
        monitor0 = new QTextEdit(centralWidget);
        monitor0->setObjectName(QStringLiteral("monitor0"));
        monitor0->setGeometry(QRect(10, 60, 511, 42));
        QFont font7;
        font7.setPointSize(18);
        monitor0->setFont(font7);
        monitor0->setFrameShape(QFrame::Box);
        monitor0->setFrameShadow(QFrame::Sunken);
        monitor0->setLineWidth(0);
        monitor0->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        monitor0->setLineWrapColumnOrWidth(0);
        monitor2 = new QTextEdit(centralWidget);
        monitor2->setObjectName(QStringLiteral("monitor2"));
        monitor2->setGeometry(QRect(530, 60, 361, 51));
        QFont font8;
        font8.setPointSize(18);
        font8.setBold(true);
        font8.setItalic(false);
        font8.setWeight(75);
        monitor2->setFont(font8);
        monitor2->setLayoutDirection(Qt::LeftToRight);
        monitor2->setFrameShape(QFrame::Box);
        monitor2->setLineWidth(0);
        monitor2->setReadOnly(true);
        clear_2 = new QPushButton(centralWidget);
        clear_2->setObjectName(QStringLiteral("clear_2"));
        clear_2->setGeometry(QRect(850, 700, 41, 31));
        clear_2->setFont(font3);
        clear_2->setIconSize(QSize(30, 30));
        mem_his = new QTextEdit(centralWidget);
        mem_his->setObjectName(QStringLiteral("mem_his"));
        mem_his->setGeometry(QRect(530, 100, 361, 631));
        mem_his->setFont(font1);
        mem_his->setLayoutDirection(Qt::RightToLeft);
        mem_his->setFrameShape(QFrame::Box);
        mem_his->setLineWidth(0);
        mem_clear_2 = new QPushButton(centralWidget);
        mem_clear_2->setObjectName(QStringLiteral("mem_clear_2"));
        mem_clear_2->setGeometry(QRect(10, 270, 91, 41));
        mem_clear_2->setFont(font4);
        mem_minus_2 = new QPushButton(centralWidget);
        mem_minus_2->setObjectName(QStringLiteral("mem_minus_2"));
        mem_minus_2->setGeometry(QRect(310, 270, 91, 41));
        mem_minus_2->setFont(font4);
        mm_read_2 = new QPushButton(centralWidget);
        mm_read_2->setObjectName(QStringLiteral("mm_read_2"));
        mm_read_2->setGeometry(QRect(110, 270, 91, 41));
        mm_read_2->setFont(font4);
        mem_plus_2 = new QPushButton(centralWidget);
        mem_plus_2->setObjectName(QStringLiteral("mem_plus_2"));
        mem_plus_2->setGeometry(QRect(210, 270, 91, 41));
        mem_plus_2->setFont(font4);
        mem_save_2 = new QPushButton(centralWidget);
        mem_save_2->setObjectName(QStringLiteral("mem_save_2"));
        mem_save_2->setGeometry(QRect(410, 270, 91, 41));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        mem_save_2->setPalette(palette3);
        mem_save_2->setFont(font4);
        mem_save_2->setAutoDefault(false);
        F_E = new QPushButton(centralWidget);
        F_E->setObjectName(QStringLiteral("F_E"));
        F_E->setGeometry(QRect(210, 220, 91, 41));
        F_E->setFont(font4);
        HYP = new QPushButton(centralWidget);
        HYP->setObjectName(QStringLiteral("HYP"));
        HYP->setGeometry(QRect(110, 220, 91, 41));
        HYP->setFont(font4);
        GRD = new QPushButton(centralWidget);
        GRD->setObjectName(QStringLiteral("GRD"));
        GRD->setGeometry(QRect(10, 220, 91, 41));
        GRD->setFont(font4);
        square_2 = new QPushButton(centralWidget);
        square_2->setObjectName(QStringLiteral("square_2"));
        square_2->setGeometry(QRect(10, 320, 93, 51));
        QFont font9;
        font9.setPointSize(15);
        square_2->setFont(font9);
        sqrt = new QPushButton(centralWidget);
        sqrt->setObjectName(QStringLiteral("sqrt"));
        sqrt->setGeometry(QRect(10, 380, 93, 51));
        sqrt->setFont(font9);
        arrow = new QPushButton(centralWidget);
        arrow->setObjectName(QStringLiteral("arrow"));
        arrow->setGeometry(QRect(10, 440, 93, 51));
        QFont font10;
        font10.setPointSize(15);
        font10.setUnderline(false);
        arrow->setFont(font10);
        arrow->setAcceptDrops(false);
        pi = new QPushButton(centralWidget);
        pi->setObjectName(QStringLiteral("pi"));
        pi->setGeometry(QRect(10, 500, 93, 51));
        pi->setFont(font7);
        Left_Pare = new QPushButton(centralWidget);
        Left_Pare->setObjectName(QStringLiteral("Left_Pare"));
        Left_Pare->setGeometry(QRect(10, 680, 93, 51));
        Left_Pare->setFont(font7);
        factorial = new QPushButton(centralWidget);
        factorial->setObjectName(QStringLiteral("factorial"));
        factorial->setGeometry(QRect(10, 560, 93, 51));
        factorial->setFont(font7);
        negate_2 = new QPushButton(centralWidget);
        negate_2->setObjectName(QStringLiteral("negate_2"));
        negate_2->setGeometry(QRect(10, 620, 93, 51));
        negate_2->setFont(font7);
        N4 = new QPushButton(centralWidget);
        N4->setObjectName(QStringLiteral("N4"));
        N4->setGeometry(QRect(110, 560, 93, 51));
        N4->setFont(font1);
        N7 = new QPushButton(centralWidget);
        N7->setObjectName(QStringLiteral("N7"));
        N7->setGeometry(QRect(110, 500, 93, 51));
        N7->setFont(font1);
        Right_Pare = new QPushButton(centralWidget);
        Right_Pare->setObjectName(QStringLiteral("Right_Pare"));
        Right_Pare->setGeometry(QRect(110, 680, 93, 51));
        Right_Pare->setFont(font7);
        power_y = new QPushButton(centralWidget);
        power_y->setObjectName(QStringLiteral("power_y"));
        power_y->setGeometry(QRect(110, 320, 93, 51));
        power_y->setFont(font9);
        power_ten = new QPushButton(centralWidget);
        power_ten->setObjectName(QStringLiteral("power_ten"));
        power_ten->setGeometry(QRect(110, 380, 93, 51));
        power_ten->setFont(font9);
        Clear_entry = new QPushButton(centralWidget);
        Clear_entry->setObjectName(QStringLiteral("Clear_entry"));
        Clear_entry->setGeometry(QRect(110, 440, 93, 51));
        Clear_entry->setFont(font9);
        N1 = new QPushButton(centralWidget);
        N1->setObjectName(QStringLiteral("N1"));
        N1->setGeometry(QRect(110, 620, 93, 51));
        N1->setFont(font1);
        N5 = new QPushButton(centralWidget);
        N5->setObjectName(QStringLiteral("N5"));
        N5->setGeometry(QRect(210, 560, 93, 51));
        N5->setFont(font1);
        N8 = new QPushButton(centralWidget);
        N8->setObjectName(QStringLiteral("N8"));
        N8->setGeometry(QRect(210, 500, 93, 51));
        N8->setFont(font1);
        N0 = new QPushButton(centralWidget);
        N0->setObjectName(QStringLiteral("N0"));
        N0->setGeometry(QRect(210, 680, 93, 51));
        N0->setFont(font1);
        sin = new QPushButton(centralWidget);
        sin->setObjectName(QStringLiteral("sin"));
        sin->setGeometry(QRect(210, 320, 93, 51));
        sin->setFont(font9);
        log = new QPushButton(centralWidget);
        log->setObjectName(QStringLiteral("log"));
        log->setGeometry(QRect(210, 380, 93, 51));
        log->setFont(font9);
        Clear = new QPushButton(centralWidget);
        Clear->setObjectName(QStringLiteral("Clear"));
        Clear->setGeometry(QRect(210, 440, 93, 51));
        Clear->setFont(font9);
        N2 = new QPushButton(centralWidget);
        N2->setObjectName(QStringLiteral("N2"));
        N2->setGeometry(QRect(210, 620, 93, 51));
        N2->setFont(font1);
        divide_2 = new QPushButton(centralWidget);
        divide_2->setObjectName(QStringLiteral("divide_2"));
        divide_2->setGeometry(QRect(410, 440, 93, 51));
        divide_2->setFont(font7);
        cos = new QPushButton(centralWidget);
        cos->setObjectName(QStringLiteral("cos"));
        cos->setGeometry(QRect(310, 320, 93, 51));
        cos->setFont(font9);
        Delete_1 = new QPushButton(centralWidget);
        Delete_1->setObjectName(QStringLiteral("Delete_1"));
        Delete_1->setGeometry(QRect(310, 440, 93, 51));
        Delete_1->setFont(font9);
        times_2 = new QPushButton(centralWidget);
        times_2->setObjectName(QStringLiteral("times_2"));
        times_2->setGeometry(QRect(410, 500, 93, 51));
        times_2->setFont(font7);
        minus_2 = new QPushButton(centralWidget);
        minus_2->setObjectName(QStringLiteral("minus_2"));
        minus_2->setGeometry(QRect(410, 560, 93, 51));
        minus_2->setFont(font7);
        Mod = new QPushButton(centralWidget);
        Mod->setObjectName(QStringLiteral("Mod"));
        Mod->setGeometry(QRect(410, 380, 93, 51));
        Mod->setFont(font9);
        N6 = new QPushButton(centralWidget);
        N6->setObjectName(QStringLiteral("N6"));
        N6->setGeometry(QRect(310, 560, 93, 51));
        N6->setFont(font1);
        Exp = new QPushButton(centralWidget);
        Exp->setObjectName(QStringLiteral("Exp"));
        Exp->setGeometry(QRect(310, 380, 93, 51));
        Exp->setFont(font9);
        tan = new QPushButton(centralWidget);
        tan->setObjectName(QStringLiteral("tan"));
        tan->setGeometry(QRect(410, 320, 93, 51));
        tan->setFont(font9);
        point_2 = new QPushButton(centralWidget);
        point_2->setObjectName(QStringLiteral("point_2"));
        point_2->setGeometry(QRect(310, 680, 93, 51));
        point_2->setFont(font7);
        plus_2 = new QPushButton(centralWidget);
        plus_2->setObjectName(QStringLiteral("plus_2"));
        plus_2->setGeometry(QRect(410, 620, 93, 51));
        plus_2->setFont(font7);
        N3 = new QPushButton(centralWidget);
        N3->setObjectName(QStringLiteral("N3"));
        N3->setGeometry(QRect(310, 620, 93, 51));
        N3->setFont(font1);
        equal_2 = new QPushButton(centralWidget);
        equal_2->setObjectName(QStringLiteral("equal_2"));
        equal_2->setGeometry(QRect(410, 680, 93, 51));
        equal_2->setFont(font7);
        N9 = new QPushButton(centralWidget);
        N9->setObjectName(QStringLiteral("N9"));
        N9->setGeometry(QRect(310, 500, 93, 51));
        N9->setFont(font1);
        mode = new QPushButton(centralWidget);
        mode->setObjectName(QStringLiteral("mode"));
        mode->setGeometry(QRect(10, 20, 93, 41));
        mode->setFont(font3);
        dms = new QPushButton(centralWidget);
        dms->setObjectName(QStringLiteral("dms"));
        dms->setGeometry(QRect(310, 380, 93, 51));
        dms->setFont(font9);
        N_Reagan = new QPushButton(centralWidget);
        N_Reagan->setObjectName(QStringLiteral("N_Reagan"));
        N_Reagan->setGeometry(QRect(110, 320, 93, 51));
        N_Reagan->setFont(font9);
        deg = new QPushButton(centralWidget);
        deg->setObjectName(QStringLiteral("deg"));
        deg->setGeometry(QRect(410, 380, 93, 51));
        deg->setFont(font9);
        ln = new QPushButton(centralWidget);
        ln->setObjectName(QStringLiteral("ln"));
        ln->setGeometry(QRect(210, 380, 93, 51));
        ln->setFont(font9);
        cos_01 = new QPushButton(centralWidget);
        cos_01->setObjectName(QStringLiteral("cos_01"));
        cos_01->setGeometry(QRect(310, 320, 93, 51));
        cos_01->setFont(font9);
        N_power = new QPushButton(centralWidget);
        N_power->setObjectName(QStringLiteral("N_power"));
        N_power->setGeometry(QRect(110, 380, 93, 51));
        N_power->setFont(font9);
        cube = new QPushButton(centralWidget);
        cube->setObjectName(QStringLiteral("cube"));
        cube->setGeometry(QRect(10, 320, 93, 51));
        cube->setFont(font9);
        reciprocal_2 = new QPushButton(centralWidget);
        reciprocal_2->setObjectName(QStringLiteral("reciprocal_2"));
        reciprocal_2->setGeometry(QRect(10, 380, 93, 51));
        reciprocal_2->setFont(font9);
        sin_01 = new QPushButton(centralWidget);
        sin_01->setObjectName(QStringLiteral("sin_01"));
        sin_01->setGeometry(QRect(210, 320, 93, 51));
        sin_01->setFont(font9);
        tan_01 = new QPushButton(centralWidget);
        tan_01->setObjectName(QStringLiteral("tan_01"));
        tan_01->setGeometry(QRect(410, 320, 93, 51));
        tan_01->setFont(font9);
        cosh = new QPushButton(centralWidget);
        cosh->setObjectName(QStringLiteral("cosh"));
        cosh->setGeometry(QRect(310, 320, 93, 51));
        cosh->setFont(font9);
        sinh = new QPushButton(centralWidget);
        sinh->setObjectName(QStringLiteral("sinh"));
        sinh->setGeometry(QRect(210, 320, 93, 51));
        sinh->setFont(font9);
        tanh = new QPushButton(centralWidget);
        tanh->setObjectName(QStringLiteral("tanh"));
        tanh->setGeometry(QRect(410, 320, 93, 51));
        tanh->setFont(font9);
        cosh_01 = new QPushButton(centralWidget);
        cosh_01->setObjectName(QStringLiteral("cosh_01"));
        cosh_01->setGeometry(QRect(310, 320, 93, 51));
        cosh_01->setFont(font9);
        sinh_01 = new QPushButton(centralWidget);
        sinh_01->setObjectName(QStringLiteral("sinh_01"));
        sinh_01->setGeometry(QRect(210, 320, 93, 51));
        sinh_01->setFont(font9);
        tanh_01 = new QPushButton(centralWidget);
        tanh_01->setObjectName(QStringLiteral("tanh_01"));
        tanh_01->setGeometry(QRect(410, 320, 93, 51));
        tanh_01->setFont(font9);
        arrow_2 = new QPushButton(centralWidget);
        arrow_2->setObjectName(QStringLiteral("arrow_2"));
        arrow_2->setGeometry(QRect(10, 440, 93, 51));
        QFont font11;
        font11.setPointSize(15);
        font11.setUnderline(true);
        arrow_2->setFont(font11);
        HYP_2 = new QPushButton(centralWidget);
        HYP_2->setObjectName(QStringLiteral("HYP_2"));
        HYP_2->setGeometry(QRect(110, 220, 93, 41));
        QFont font12;
        font12.setPointSize(12);
        font12.setUnderline(true);
        HYP_2->setFont(font12);
        MainWindow->setCentralWidget(centralWidget);
        monitor2->raise();
        mem_his->raise();
        monitor3->raise();
        clear_3->raise();
        clear_2->raise();
        percent->raise();
        clear_entry->raise();
        radical_sign->raise();
        clear->raise();
        square->raise();
        delete_2->raise();
        reciprocal->raise();
        divide->raise();
        history->raise();
        memory->raise();
        mem_clear->raise();
        mm_read->raise();
        mem_plus->raise();
        mem_minus->raise();
        mem_save->raise();
        monitor1->raise();
        number_7->raise();
        number_6->raise();
        times->raise();
        number_9->raise();
        number_4->raise();
        minus->raise();
        number_8->raise();
        number_5->raise();
        number_1->raise();
        point->raise();
        plus->raise();
        number_3->raise();
        negate->raise();
        equal->raise();
        number_2->raise();
        number_0->raise();
        monitor0->raise();
        mem_clear_2->raise();
        mem_minus_2->raise();
        mm_read_2->raise();
        mem_plus_2->raise();
        mem_save_2->raise();
        F_E->raise();
        HYP->raise();
        GRD->raise();
        square_2->raise();
        sqrt->raise();
        arrow->raise();
        pi->raise();
        Left_Pare->raise();
        factorial->raise();
        negate_2->raise();
        N4->raise();
        N7->raise();
        Right_Pare->raise();
        power_y->raise();
        power_ten->raise();
        Clear_entry->raise();
        N1->raise();
        N5->raise();
        N8->raise();
        N0->raise();
        sin->raise();
        log->raise();
        Clear->raise();
        N2->raise();
        divide_2->raise();
        cos->raise();
        Delete_1->raise();
        times_2->raise();
        minus_2->raise();
        Mod->raise();
        N6->raise();
        Exp->raise();
        tan->raise();
        point_2->raise();
        plus_2->raise();
        N3->raise();
        equal_2->raise();
        N9->raise();
        mode->raise();
        dms->raise();
        N_Reagan->raise();
        deg->raise();
        ln->raise();
        cos_01->raise();
        N_power->raise();
        cube->raise();
        reciprocal_2->raise();
        sin_01->raise();
        tan_01->raise();
        cosh->raise();
        sinh->raise();
        tanh->raise();
        cosh_01->raise();
        sinh_01->raise();
        tanh_01->raise();
        arrow_2->raise();
        HYP_2->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 902, 26));
        menu = new QMenu(menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menu->menuAction());
        menu->addAction(action_C);
        menu->addAction(action_D);
        menu->addAction(action_H);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        action_C->setText(QApplication::translate("MainWindow", "\350\277\236\346\216\245(&C)", Q_NULLPTR));
        action_D->setText(QApplication::translate("MainWindow", "\346\226\255\345\274\200\350\277\236\346\216\245(&D)", Q_NULLPTR));
        action_H->setText(QApplication::translate("MainWindow", "\345\270\256\345\212\251(&H)", Q_NULLPTR));
        percent->setText(QApplication::translate("MainWindow", "%", Q_NULLPTR));
        clear_entry->setText(QApplication::translate("MainWindow", "CE", Q_NULLPTR));
        radical_sign->setText(QApplication::translate("MainWindow", "\342\210\232", Q_NULLPTR));
        clear->setText(QApplication::translate("MainWindow", "C", Q_NULLPTR));
        square->setText(QApplication::translate("MainWindow", "x\302\262", Q_NULLPTR));
        delete_2->setText(QApplication::translate("MainWindow", "delete", Q_NULLPTR));
        reciprocal->setText(QApplication::translate("MainWindow", "1/x", Q_NULLPTR));
        divide->setText(QApplication::translate("MainWindow", "\303\267", Q_NULLPTR));
        history->setText(QApplication::translate("MainWindow", "\345\216\206\345\217\262\347\272\252\345\275\225", Q_NULLPTR));
        memory->setText(QApplication::translate("MainWindow", "\345\255\230\345\202\250", Q_NULLPTR));
        mem_clear->setText(QApplication::translate("MainWindow", "MC", Q_NULLPTR));
        mm_read->setText(QApplication::translate("MainWindow", "MR", Q_NULLPTR));
        mem_plus->setText(QApplication::translate("MainWindow", "M+", Q_NULLPTR));
        mem_minus->setText(QApplication::translate("MainWindow", "M-", Q_NULLPTR));
        mem_save->setText(QApplication::translate("MainWindow", "MS", Q_NULLPTR));
        clear_3->setText(QString());
        monitor1->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:36pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", Q_NULLPTR));
        monitor3->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\345\260\232\346\227\240\345\216\206\345\217\262\347\272\252\345\275\225</p></body></html>", Q_NULLPTR));
        number_7->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        number_6->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        times->setText(QApplication::translate("MainWindow", "\303\227", Q_NULLPTR));
        number_9->setText(QApplication::translate("MainWindow", "9", Q_NULLPTR));
        number_4->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        minus->setText(QApplication::translate("MainWindow", "-", Q_NULLPTR));
        number_8->setText(QApplication::translate("MainWindow", "8", Q_NULLPTR));
        number_5->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        number_1->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        point->setText(QApplication::translate("MainWindow", ".", Q_NULLPTR));
        plus->setText(QApplication::translate("MainWindow", "+", Q_NULLPTR));
        number_3->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        negate->setText(QApplication::translate("MainWindow", "+/-", Q_NULLPTR));
        equal->setText(QApplication::translate("MainWindow", "=", Q_NULLPTR));
        number_2->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        number_0->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        monitor0->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", Q_NULLPTR));
        monitor2->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\345\206\205\345\255\230\344\270\255\346\262\241\346\234\211\345\206\205\345\256\271</p></body></html>", Q_NULLPTR));
        clear_2->setText(QString());
        mem_his->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", Q_NULLPTR));
        mem_clear_2->setText(QApplication::translate("MainWindow", "MC", Q_NULLPTR));
        mem_minus_2->setText(QApplication::translate("MainWindow", "M-", Q_NULLPTR));
        mm_read_2->setText(QApplication::translate("MainWindow", "MR", Q_NULLPTR));
        mem_plus_2->setText(QApplication::translate("MainWindow", "M+", Q_NULLPTR));
        mem_save_2->setText(QApplication::translate("MainWindow", "MS", Q_NULLPTR));
        F_E->setText(QApplication::translate("MainWindow", "F-E", Q_NULLPTR));
        HYP->setText(QApplication::translate("MainWindow", "HYP", Q_NULLPTR));
        GRD->setText(QApplication::translate("MainWindow", "RAD", Q_NULLPTR));
        square_2->setText(QApplication::translate("MainWindow", "x\302\262", Q_NULLPTR));
        sqrt->setText(QApplication::translate("MainWindow", "\342\210\232", Q_NULLPTR));
        arrow->setText(QApplication::translate("MainWindow", "\342\206\221", Q_NULLPTR));
        pi->setText(QApplication::translate("MainWindow", "\317\200", Q_NULLPTR));
        Left_Pare->setText(QApplication::translate("MainWindow", "(", Q_NULLPTR));
        factorial->setText(QApplication::translate("MainWindow", "n!", Q_NULLPTR));
        negate_2->setText(QApplication::translate("MainWindow", "+/-", Q_NULLPTR));
        N4->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        N7->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        Right_Pare->setText(QApplication::translate("MainWindow", ")", Q_NULLPTR));
        power_y->setText(QApplication::translate("MainWindow", "x\342\201\277", Q_NULLPTR));
        power_ten->setText(QApplication::translate("MainWindow", "10\342\201\277", Q_NULLPTR));
        Clear_entry->setText(QApplication::translate("MainWindow", "CE", Q_NULLPTR));
        N1->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        N5->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        N8->setText(QApplication::translate("MainWindow", "8", Q_NULLPTR));
        N0->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        sin->setText(QApplication::translate("MainWindow", "sin", Q_NULLPTR));
        log->setText(QApplication::translate("MainWindow", "log", Q_NULLPTR));
        Clear->setText(QApplication::translate("MainWindow", "C", Q_NULLPTR));
        N2->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        divide_2->setText(QApplication::translate("MainWindow", "\303\267", Q_NULLPTR));
        cos->setText(QApplication::translate("MainWindow", "cos", Q_NULLPTR));
        Delete_1->setText(QApplication::translate("MainWindow", "delete", Q_NULLPTR));
        times_2->setText(QApplication::translate("MainWindow", "\303\227", Q_NULLPTR));
        minus_2->setText(QApplication::translate("MainWindow", "-", Q_NULLPTR));
        Mod->setText(QApplication::translate("MainWindow", "Mod", Q_NULLPTR));
        N6->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        Exp->setText(QApplication::translate("MainWindow", "Exp", Q_NULLPTR));
        tan->setText(QApplication::translate("MainWindow", "tan", Q_NULLPTR));
        point_2->setText(QApplication::translate("MainWindow", ".", Q_NULLPTR));
        plus_2->setText(QApplication::translate("MainWindow", "+", Q_NULLPTR));
        N3->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        equal_2->setText(QApplication::translate("MainWindow", "=", Q_NULLPTR));
        N9->setText(QApplication::translate("MainWindow", "9", Q_NULLPTR));
        mode->setText(QApplication::translate("MainWindow", "\347\247\221\345\255\246", Q_NULLPTR));
        dms->setText(QApplication::translate("MainWindow", "dms", Q_NULLPTR));
        N_Reagan->setText(QApplication::translate("MainWindow", "\342\201\277\342\210\232x", Q_NULLPTR));
        deg->setText(QApplication::translate("MainWindow", "deg", Q_NULLPTR));
        ln->setText(QApplication::translate("MainWindow", "ln", Q_NULLPTR));
        cos_01->setText(QApplication::translate("MainWindow", "cos\342\201\273\302\271", Q_NULLPTR));
        N_power->setText(QApplication::translate("MainWindow", "e\342\201\277", Q_NULLPTR));
        cube->setText(QApplication::translate("MainWindow", "x\302\263", Q_NULLPTR));
        reciprocal_2->setText(QApplication::translate("MainWindow", "1/x", Q_NULLPTR));
        sin_01->setText(QApplication::translate("MainWindow", "sin\342\201\273\302\271", Q_NULLPTR));
        tan_01->setText(QApplication::translate("MainWindow", "tan\342\201\273\302\271", Q_NULLPTR));
        cosh->setText(QApplication::translate("MainWindow", "cosh", Q_NULLPTR));
        sinh->setText(QApplication::translate("MainWindow", "sinh", Q_NULLPTR));
        tanh->setText(QApplication::translate("MainWindow", "tanh", Q_NULLPTR));
        cosh_01->setText(QApplication::translate("MainWindow", "cosh\342\201\273\302\271", Q_NULLPTR));
        sinh_01->setText(QApplication::translate("MainWindow", "sinh\342\201\273\302\271", Q_NULLPTR));
        tanh_01->setText(QApplication::translate("MainWindow", "tanh\342\201\273\302\271", Q_NULLPTR));
        arrow_2->setText(QApplication::translate("MainWindow", "\342\206\221", Q_NULLPTR));
        HYP_2->setText(QApplication::translate("MainWindow", "HYP", Q_NULLPTR));
        menu->setTitle(QApplication::translate("MainWindow", "\350\256\276\347\275\256", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
